"use strict";
const KEY="hnVisitPredictorV1";
const state={current:497,goal:500,snapshots:[]};
const $=id=>document.getElementById(id);
function status(t){$("status").textContent=t}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){console.error("Could not save predictor data:",e);status("Save failed")}}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||"null");if(x){if(Number.isInteger(x.current)&&x.current>=0)state.current=x.current;if(Number.isInteger(x.goal)&&x.goal>0)state.goal=x.goal;if(Array.isArray(x.snapshots))state.snapshots=x.snapshots.filter(s=>Number.isInteger(s.visits)&&s.visits>=0&&typeof s.time==="string")}}catch(e){console.error("Could not load predictor data:",e)}$("goal").value=state.goal;$("visits").value=state.current;setDate();render()}
function setDate(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());$("date").value=d.toISOString().slice(0,16)}
function rate(){if(state.snapshots.length<2)return null;const a=[...state.snapshots].sort((x,y)=>new Date(x.time)-new Date(y.time));const days=(new Date(a.at(-1).time)-new Date(a[0].time))/86400000;const gain=a.at(-1).visits-a[0].visits;return days>0&&gain>0?gain/days:null}
function advance(){while(state.current>=state.goal)state.goal+=100;$("goal").value=state.goal}
function render(){advance();const pct=Math.min(100,state.current/state.goal*100);$("current").textContent=state.current.toLocaleString();$("goalText").textContent=`/ ${state.goal.toLocaleString()}`;$("progress").style.width=pct+"%";$("percent").textContent=pct.toFixed(1)+"% of goal";const r=rate(),remaining=state.goal-state.current;if(remaining<=0){$("prediction").textContent="Goal reached 🎉"}else if(!r){$("prediction").textContent="Waiting for more data";$("details").textContent="Add at least two snapshots with increasing visits to calculate visits/day."}else{const eta=new Date(Date.now()+remaining/r*86400000);$("prediction").textContent=eta.toLocaleString(undefined,{dateStyle:"medium",timeStyle:"short"});$("details").textContent=`Average rate: ${r.toFixed(2)} visits/day • ${remaining} visits remaining.`}$("count").textContent=`${state.snapshots.length} snapshot${state.snapshots.length===1?"":"s"}`;const h=$("history");h.innerHTML="";if(!state.snapshots.length){h.innerHTML='<div class="empty">No snapshots yet.</div>';return} [...state.snapshots].sort((a,b)=>new Date(b.time)-new Date(a.time)).forEach((s,i)=>{const row=document.createElement("div");row.className="history-row";const d=document.createElement("span");d.textContent=new Date(s.time).toLocaleString();const v=document.createElement("b");v.textContent=s.visits.toLocaleString();const rm=document.createElement("button");rm.textContent="Remove";rm.onclick=()=>{state.snapshots.splice(state.snapshots.findIndex(x=>x===s),1);save();render();status("Snapshot removed")};row.append(d,v,rm);h.append(row)})}
$("saveGoal").onclick=()=>{const n=Number($("goal").value);if(!Number.isInteger(n)||n<1){status("Enter a valid goal");return}state.goal=n;save();render();status("Goal saved")};
$("add").onclick=()=>{const v=Number($("visits").value),t=$("date").value;if(!Number.isInteger(v)||v<0||!t){status("Enter valid data");return}state.current=v;state.snapshots.push({visits:v,time:new Date(t).toISOString()});save();render();status("Snapshot added")};
$("update").onclick=()=>{const v=Number($("visits").value);if(!Number.isInteger(v)||v<0){status("Enter valid visits");return}state.current=v;save();render();status("Current visits updated")};
$("clear").onclick=()=>{if(!confirm("Clear all visit snapshots?"))return;state.snapshots=[];save();render();status("History cleared")};
load();
